### ISSUE TITLE
Auth fail

### ISSUE THREAD

**Issue by IldeNet** [Sea-n/LINE-to-TG#1]
I've done the steps and Auth Fail appears when I run hook.php

**Comment by Sea-n** [comment]
You didn't setup successfully.

**Comment by IldeNet** [comment]
if I set the webhook separately, telegram shows message of set correctly and the control panel of lineapp also.
But it still does not work because I think the chat to follow is badly written.
If I run hook from the browser I get an error in the authentication.
Is it possible to contact you by telegram? my nick is @ildenet
